create table if not exists url_mapping (
    id bigint generated by default as identity primary key,
    short_code varchar(16) unique,
    long_url varchar(2048) not null unique,
    created_at timestamp with time zone not null
);

create index if not exists idx_url_mapping_short_code on url_mapping(short_code);
